name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/*"
      - "tests/*"
  pull_request:
    paths:
      - "src/*"
      - "tests/*"

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Coverage
        run: |
          pip install coverage
      - name: Run Tests
        run: |
          coverage run tests/test_credentials_manager.py
          coverage report -m

      - name: Create coverage folder
        run: |
          mkdir -p coverage

      - name: Create Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage/coverage.svg

      - name: Publish coverage report to coverage-badge branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: coverage-badge
          folder: coverage
